### ISSUE TITLE
Czech translate

### ISSUE THREAD

**Issue by tkantor81** [kingdomcomecodex/kingdomcomecodex.github.io#1]
"Welcome to the online Kingdom Come: Deliverance Codex reader. Made using language and image files from the game with love by @nachazo. You can send feedback and issues in GitHub project.
Selected language is: ENGLISH. You can change the language clicking in the desired flag on the list."

Should be:

"Vítejte v on-line Kingdom Come: Deliverance kodexu. Vytvořeno pomocí jazykových a obrazových souborů ze hry s láskou @nachazo. V projektu GitHub můžete odeslat zpětnou vazbu a nahlásit problémy.

Zvolený jazyk je: ČEŠTINA. Jazyk můžete změnit kliknutím na vlajku v seznamu."

**Comment by tkantor81** [comment]
"This site use cookies for store last article read, the language and if you mark as read articles. If you want to delete that from your browser, remove all stored kcd_codex_* cookies."

Should be:

"Tyto stránky používají soubory cookies pro zapamatování naposledy čteného článku, nastaveného jazyka a označení přečtených článků. Chcete-li to z vašeho prohlížeče odstranit, smažte všechny uložené soubory cookie kcd_codex_*."

**Comment by nachazo** [comment]
Hi! Thanks for the corrections. Just pushed with the corrected texts to the repo in 957c7964c55708c3594362929be445e1712e30d9 commit :)
