### ISSUE TITLE
Missing font for some letters

### ISSUE THREAD

**Issue by tkantor81** [kingdomcomecodex/kingdomcomecodex.github.io#2]
There are missing font for some letters in Czech language like ě, ř, č, ů, ň, ď.

**Comment by nachazo** [comment]
Thanks for the feedback! I know, it's about the truetype font "1529 Champ Fleury". For chinese or russian I directly changed the font. But I prefer to mantain it for CS, the look is nice instead these letters not showing (much beter that change the whole font).
