### ISSUE TITLE
Missing pictures in Czech translation

### ISSUE THREAD

**Issue by tkantor81** [kingdomcomecodex/kingdomcomecodex.github.io#3]
There are some missing pictures in Czech translation, for example in "Tutorial" section - "Combat" article.

**Comment by nachazo** [comment]
In fact I never managed to found the correct images in the data files. "Combat" section is a bit strange in the XML files (is different to anothers) so some errors are shown in that. Anyways I used the same image that in another languages for not show "the error". Thanks for feedback.

**Comment by nachazo** [comment]
519c80e7064fca0c7ee9aa48fb40d6c628fd12ef

**Comment by tkantor81** [comment]
Missing picture is in Tutorials - Combat - Advanced techniques (Boj - pokročilé techniky) too.
And this page is whole missing in other translations.
