### ISSUE TITLE
Polish title page and other translations

### ISSUE THREAD

**Issue by Matik7** [kingdomcomecodex/kingdomcomecodex.github.io#4]
The text in Polish version is obviously translated by Google Translator, and that's very bad. See my corrected edit:

> Witamy w internetowej przeglądarce wpisów z kodeksu Kingdom Come: Deliverance. Stworzona z miłością przez @nachazo przy pomocy języków i grafik z samej gry. Opinie i problemy wysyłać można poprzez stronę projektu GitHub.

> Wybrany język to POLSKI. Aby zmienić język wybierz jedną z dostępnych lokalizacji poniżej.

Also change Map Online from "Mapuj online" to "Interaktywna mapa".

I haven't encountered any other issues.

**Comment by Matik7** [comment]
Also when opening the location on a map the message is fine, but the buttons aren't quite right.
> Tak! Zawsze otwieraj odnośniki.
> Tak! Otwórz odnośnik jednorazowo.
> Nie! Wolę odkrywać sam.

Also the title of the notification should say "Zaraz zobaczysz spoilery..."

**Comment by nachazo** [comment]
Sorry for the delay. I will make and update with the new codex items and will fix that.
Thanks!

**Comment by Matik7** [comment]
No problem! I'm always glad to help.
